name: recipe_book_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  dartx: ^1.2.0
  dotted_line: ^3.2.2
  extended_image: ^8.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  image_picker: ^1.1.2
  injectable: ^2.4.2
  intl: any
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.3.0
  supabase_flutter: ^2.5.6
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0
  build_runner: any
  flutter_gen: any
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  generate: true
